[package]
name = "aws-iot-device-sdk-rust"
version = "0.1.0"
authors = ["Arnstein Kleven <arnsteinkleven@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqtt = "0.31.0"
serde_json = "1.0"
