[package]
name = "aws-iot-device-sdk-rust"
description = "An easy to use SDK for connecting to AWS IoT Core."
documentation = "https://docs.rs/aws-iot-device-sdk-rust"
repository = "https://github.com/arnstein/aws-iot-device-sdk-rust"
license = "MIT"
version = "1.0.0"
authors = ["Arnstein Kleven <arnsteinkleven@gmail.com>"]
edition = "2018"

include = [
    "src/lib.rs",
    "src/client.rs",
    "src/shadow.rs",
    "Cargo.toml",
    "README.md"
    ]


[features]
default = ["async"]
async = ["async-trait"]

[dependencies]
rumqttc = "0.10.0"
serde_json = "1.0"
crossbeam-channel = "0.5.1"
mqtt4bytes = "0.1.6"
async-channel = { version = "1.6.1" }
async-trait = { version = "0.1.40", optional = true }
tokio = { version = "1.14.0", features = ["rt-multi-thread", "sync", "macros", "net", "time"] }
